import { ERPModule } from '../context/ERPContext';

export const MODULE_PATHS: Record<ERPModule, string> = {
  'Dashboard': '/',
  'CRM & Sales': '/sales',
  'Purchase': '/purchase',
  'Raw Material': '/raw-material',
  'Production': '/production',
  'Quality Control': '/quality-control',
  'Finished Goods': '/finished-goods',
  'Inventory': '/inventory',
  'Dispatch & Logistics': '/dispatch',
  'Customers': '/customers',
  'Suppliers': '/suppliers',
  'Finance & Accounts': '/finance',
  'Expenses': '/expenses',
  'Employees': '/employees',
  'Maintenance': '/maintenance',
  'Documents': '/documents',
  'Reports & Analytics': '/reports',
  'Settings': '/settings',
};

export const PATH_TO_MODULE: Record<string, ERPModule> = {
  '/': 'Dashboard',
  '/dashboard': 'Dashboard',
  '/sales': 'CRM & Sales',
  '/crm-sales': 'CRM & Sales',
  '/purchase': 'Purchase',
  '/raw-material': 'Raw Material',
  '/production': 'Production',
  '/quality-control': 'Quality Control',
  '/finished-goods': 'Finished Goods',
  '/inventory': 'Inventory',
  '/dispatch': 'Dispatch & Logistics',
  '/dispatch-logistics': 'Dispatch & Logistics',
  '/customers': 'Customers',
  '/suppliers': 'Suppliers',
  '/finance': 'Finance & Accounts',
  '/finance-accounts': 'Finance & Accounts',
  '/expenses': 'Expenses',
  '/employees': 'Employees',
  '/maintenance': 'Maintenance',
  '/documents': 'Documents',
  '/reports': 'Reports & Analytics',
  '/reports-analytics': 'Reports & Analytics',
  '/settings': 'Settings',
};
